### ISSUE TITLE
incorrect rank of classification 

### ISSUE THREAD

**Issue by nhoffman** [nhoffman/bioy#31]
When the number of species over the ID threshold exceeds the species count threshold, a genus-level name is returned, but the rank is still species - the name and the rank should agree.

**Comment by crosenth** [comment]
The target_rank (or threshold_rank) is the lowest rank of a sometimes mutli-rank assignment name.  We will replace target_rank with the opposite, highest rank, and name the new column condensed_rank.

**Comment by crosenth** [comment]
target_rank -> best_rank

best_rank is the most common condensed_id rank.
