### ISSUE TITLE
fix --version argument switch

### ISSUE THREAD

**Issue by crosenth** [nhoffman/bioy#44]
https://github.com/nhoffman/bioy/blob/master/version.py

**Comment by crosenth** [comment]
Also see https://github.com/fhcrc/deenurp/issues/31

**Comment by nhoffman** [comment]
File above has reference to "deenurp"

https://github.com/nhoffman/bioy/blob/master/version.py#L55

**Comment by crosenth** [comment]
Fixed.  Let's leave this ticket open until I create some test cases.
